AllCops:
  Excludes:
    - db/**
    - config/initializers/simple_form.rb
    - config/initializers/simple_form_bootstrap.rb

Metrics/LineLength:
  Enabled: false
Style/StringLiterals:
  Enabled: false
